create table if not exists public.app_games (
  id bigint generated by default as identity primary key,
  game_date date not null,
  game_time text,
  location text,
  mvp text,
  payload jsonb not null,
  created_at timestamp with time zone default now()
);

alter table public.app_games enable row level security;

drop policy if exists "app_games_select_authenticated" on public.app_games;
drop policy if exists "app_games_insert_admin" on public.app_games;
drop policy if exists "app_games_delete_admin" on public.app_games;

create policy "app_games_select_authenticated"
on public.app_games
for select
to authenticated
using (true);

create policy "app_games_insert_admin"
on public.app_games
for insert
to authenticated
with check (
  exists (
    select 1
    from public.players p
    where p.user_id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "app_games_delete_admin"
on public.app_games
for delete
to authenticated
using (
  exists (
    select 1
    from public.players p
    where p.user_id = auth.uid()
    and p.role = 'admin'
  )
);
