alter table public.players
add column if not exists finance_responsible boolean default false;

alter table public.settings
add column if not exists cash_balance numeric default 0;

create table if not exists public.cash_movements (
  id bigint generated by default as identity primary key,
  type text not null,
  amount numeric not null,
  description text not null,
  balance_after numeric not null default 0,
  created_by text,
  created_at timestamp with time zone default now()
);

alter table public.cash_movements enable row level security;

drop policy if exists "cash_movements_select_allowed" on public.cash_movements;
drop policy if exists "cash_movements_insert_allowed" on public.cash_movements;
drop policy if exists "cash_movements_delete_admin" on public.cash_movements;

create policy "cash_movements_select_allowed"
on public.cash_movements
for select
to authenticated
using (
  exists (
    select 1 from public.players p
    where p.user_id = auth.uid()
    and (p.role = 'admin' or p.finance_responsible = true)
  )
);

create policy "cash_movements_insert_allowed"
on public.cash_movements
for insert
to authenticated
with check (
  exists (
    select 1 from public.players p
    where p.user_id = auth.uid()
    and (p.role = 'admin' or p.finance_responsible = true)
  )
);

create policy "cash_movements_delete_admin"
on public.cash_movements
for delete
to authenticated
using (
  exists (
    select 1 from public.players p
    where p.user_id = auth.uid()
    and p.role = 'admin'
  )
);
