create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  message text not null,
  type text default 'info',
  audience text default 'all',
  created_by text,
  created_at timestamp with time zone default now()
);

alter table public.app_notifications enable row level security;

drop policy if exists "app_notifications_select_authenticated" on public.app_notifications;
drop policy if exists "app_notifications_insert_authenticated" on public.app_notifications;
drop policy if exists "app_notifications_delete_admin" on public.app_notifications;

create policy "app_notifications_select_authenticated"
on public.app_notifications
for select
to authenticated
using (true);

create policy "app_notifications_insert_authenticated"
on public.app_notifications
for insert
to authenticated
with check (true);

create policy "app_notifications_delete_admin"
on public.app_notifications
for delete
to authenticated
using (
  exists (
    select 1 from public.players p
    where p.user_id = auth.uid()
    and p.role = 'admin'
  )
);
