create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  details jsonb default '{}'::jsonb,
  actor_email text,
  actor_player_id text,
  created_at timestamp with time zone default now()
);

alter table public.audit_logs enable row level security;

drop policy if exists "audit_logs_select_admin" on public.audit_logs;
drop policy if exists "audit_logs_insert_authenticated" on public.audit_logs;

create policy "audit_logs_select_admin"
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1 from public.players p
    where p.user_id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "audit_logs_insert_authenticated"
on public.audit_logs
for insert
to authenticated
with check (true);
